name: test-win-x86_64.yml

on:
  # push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022

    steps:

    - name: Download audios-to-dataset
      run: |
        Invoke-WebRequest -Uri https://github.com/crs-org/audios-to-dataset/releases/download/v0.1.0/audios-to-dataset_x86_64_msvc_windows.zip -OutFile audios-to-dataset.zip
        Expand-Archive -Path audios-to-dataset.zip -DestinationPath ./
        Remove-Item audios-to-dataset.zip

    - name: Check audios-to-dataset
      run: |
        ./audios-to-dataset.exe --help

    - name: Download extract-audio
      run: |
        Invoke-WebRequest -Uri https://github.com/crs-org/extract-audio/releases/download/v0.2.0/extract-audio_x86_64_msvc_windows.zip -OutFile extract-audio.zip
        Expand-Archive -Path extract-audio.zip -DestinationPath ./
        Remove-Item extract-audio.zip

    - name: Check extract-audio
      run: |
        ./extract-audio.exe --help

    - name: Download parquet data
      run: |
        mkdir test-data
        Invoke-WebRequest -Uri https://huggingface.co/datasets/speech-uk/voice-of-america/resolve/main/data/train-00000-of-00083.parquet -OutFile test-data/train-00000-of-00083.parquet

    - name: Check test-data
      run: tree /f test-data
    
    - name: Grant access
      run: |
        mkdir test-wavs
        icacls test-data /grant "Users:F"
        icacls test-wavs /grant "Users:F"
        icacls extract-audio.exe /grant "Users:F"

    - name: Trust extract-audio.exe executable
      run: |
        $path = (Get-Command ./extract-audio.exe).Source
        $cert = Get-AuthenticodeSignature $path
        if ($cert.Status -ne 'Valid') {
            Write-Host "Signing certificate is not valid. Trusting the executable..."
            Set-ExecutionPolicy Bypass -Scope Process -Force
            Unblock-File -Path $path
        } else {
            Write-Host "Signing certificate is valid. No action needed."
        }

    - name: See permissions
      run: |
        Get-Acl -Path ./extract-audio.exe | Format-List

    - name: Unpack parquet data
      run: |
        ./extract-audio.exe --input test-data --output test-wavs --format parquet

    - name: Check unpacked data
      run: tree /f test-wavs

    - name: Test case 1 (audios to parquet)
      run: |
        ./audios-to-dataset.exe --input test-wavs --output ds-parquet --format parquet
        tree /f ds-parquet/
    
    - name: Test case 2 (audios to duckdb)
      run: |
        ./audios-to-dataset.exe --input test-wavs --output ds-duckdb --format duckdb
        tree /f ds-duckdb/
